export const SIGN_IN = 'SIGN_IN'
export const AUTH_CONFIRM = 'AUTH_CONFIRM'
export const USER_INFO = 'USER_INFO'
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD'
export const CONFIG = 'CONFIG'
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const ASYNC_LOADING = 'ASYNC_LOADING'
export const NOTIFY_OPEN = 'NOTIFY_OPEN'
export const USERS_LIST = 'USERS_LIST'
export const USERS_ITEM = 'USERS_ITEM'
export const USERS_UPDATE = 'USERS_UPDATE'
export const USERS_CREATE = 'USERS_CREATE'
export const USERS_DELETE = 'USERS_DELETE'
export const USERS_GROUP = 'USERS_GROUP'

export const HOTEL_LIST = 'HOTEL_LIST'
export const HOTEL_ITEM = 'HOTEL_ITEM'

