export const HOTEL_LIST = 'hotelList'
export const HOTEL_UPDATE = 'hotelUpdate'
export const HOTEL_CREATE = 'hotelCreate'
export const USER_INFO = 'userInfo'

export const CLIENT_LIST = 'clientList'
export const CLIENT_UPDATE = 'clientUpdate'
export const CLIENT_CREATE = 'clientCreate'
export const CLIENT_ITEM = 'clientItem'
export const CLIENT_DELETE = 'clientDelete'

export const APPLICATION_LIST = 'applicationList'
export const APPLICATION_UPDATE = 'applicationUpdate'
export const APPLICATION_CREATE = 'applicationCreate'
export const APPLICATION_ITEM = 'applicationItem'
export const APPLICATION_DELETE = 'applicationDelete'
export const APPLICATION_CONFIRM = 'applicationConfirm'
export const APPLICATION_REJECT = 'applicationReject'

export const CLIENT_INFO_LIST = 'clientInfoList'
export const CLIENT_INFO_UPDATE = 'clientInfoUpdate'
export const CLIENT_INFO_CREATE = 'clientInfoCreate'
export const CLIENT_INFO_ITEM = 'clientInfoItem'
export const CLIENT_INFO_DELETE = 'clientInfoDelete'

export const EMPLOYEES_LIST = 'employeesList'
export const EMPLOYEES_ITEM = 'employeesUpdate'
export const EMPLOYEES_CREATE = 'employeesCreate'
export const EMPLOYEES_UPDATE = 'employeesItem'
export const EMPLOYEES_DELETE = 'employeesDelete'

export const ROLE_LIST = 'roleList'
export const ROLE_ITEM = 'roleItem'
export const ROLE_CREATE = 'roleCreate'
export const ROLE_UPDATE = 'roleUpdate'
export const ROLE_DELETE = 'roleDelete'

export const GROUP_LIST = 'groupList'
export const GROUP_ITEM = 'groupItem'
export const GROUP_CREATE = 'groupCreate'
export const GROUP_UPDATE = 'groupUpdate'
export const GROUP_DELETE = 'groupDelete'

export const EXPERT_EXPERTISE_LIST = 'expertExpertiseList'
export const EXPERT_EXPERTISE_ITEM = 'expertExpertiseItem'
export const EXPERT_EXPERTISE_CREATE = 'expertExpertiseCreate'
export const EXPERT_EXPERTISE_UPDATE = 'expertExpertiseUpdate'
export const EXPERT_EXPERTISE_DELETE = 'expertExpertiseDelete'

export const EXPERT_PLACE_LIST = 'expertPlaceList'
export const EXPERT_PLACE_ITEM = 'expertPlaceItem'
export const EXPERT_PLACE_CREATE = 'expertPlaceCreate'
export const EXPERT_PLACE_UPDATE = 'expertPlaceUpdate'
export const EXPERT_PLACE_DELETE = 'expertPlaceDelete'

export const COMMISSION_LIST = 'expertCommissionList'
export const COMMISSION_ITEM = 'expertCommissionItem'
export const COMMISSION_CREATE = 'expertCommissionCreate'
export const COMMISSION_UPDATE = 'expertCommissionUpdate'
export const COMMISSION_DELETE = 'expertCommissionDelete'

export const PERMISSION_LIST = 'permissionList'
