export const HOTEL_LIST = 'hotelList'
export const HOTEL_UPDATE = 'hotelUpdate'
export const HOTEL_CREATE = 'hotelCreate'
export const USER_INFO = 'userInfo'

export const ROOM_LIST = 'roomList'
export const ROOM_TYPE_LIST = 'roomTypeList'
export const ROOM_UPDATE = 'roomUpdate'
export const ROOM_CREATE = 'roomCreate'
export const ROOM_ITEM = 'roomItem'

export const CLIENT_LIST = 'clientList'
export const CLIENT_UPDATE = 'clientUpdate'
export const CLIENT_CREATE = 'clientCreate'
export const CLIENT_ITEM = 'clientItem'

export const RATES_LIST = 'ratesList'
export const RATES_UPDATE = 'ratesUpdate'
export const RATES_CREATE = 'ratesCreate'
export const RATES_ITEM = 'ratesItem'

export const RESERVATION_LIST = 'reservationList'
export const RESERVATION_UPDATE = 'reservationUpdate'
export const RESERVATION_CREATE = 'reservationCreate'
export const PLACING_LIST = 'placingList'
